
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec202110d
    username: postgres
    password: postgres
    
  mail:
      host: smtp.gmail.com
      port: 587
      username: yusuke.matsumoto@rakus-partners.co.jp
      password: xzardrqjbqryldto
      properties:
        mail:
          smtp:
            auth: true
            starttls.enable: true
